### PR TITLE
formatting pls

### PR DESCRIPTION
**Pull request by FishyFing**

### CODE REVIEW

**Comment by Zeludon** [comment]
Ehh two separate full code blocks seems overkill.

**Comment by FishyFing** [comment]
and this looks ugly https://i.fishyfing.xyz/lhi58.png

**Comment by Zeludon** [comment]
and this looks better to you? https://my.mixtape.moe/squhek.png

**Comment by FishyFing** [comment]
perfect 5/7. but no lol

**Comment by Zeludon** [comment]
that is the formatting suggested in your pull ;/, not mine.

**Comment by FishyFing** [comment]
i saw @Zeludon 
is this better?

**Comment by Zeludon** [comment]
Now its slowly turning into Macs eval, I personally like the current output, might just close this ¯\_(ツ)_/¯,

**Comment by FishyFing** [comment]
true.

**Pull request closed without merging**
